LRQA-70274 | master
patriciajeanperez/liferay-portal pull request #452
Opened 2021-10-08 23:52 UTC by epark18

https://issues.liferay.com/browse/LRQA-70274

2021-10-08 23:52 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-10-08 23:52 UTC, epark18 commented
ci:test:sf

2021-10-08 23:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d6cb8482c0f7c5575a3b603930ba13fe23650625">d6cb8482c0f7c5575a3b603930ba13fe23650625</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/epark18/liferay-portal/tree/LRQA-70274">LRQA-70274</a><br/>Branch GIT ID: <a href="https://github.com/epark18/liferay-portal/commit/bc58141de5785fc7a8d70efbce3ccf81e394b751">bc58141de5785fc7a8d70efbce3ccf81e394b751</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/713/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/713/jenkins-report.html">here</a>.</h5></details></html>

2021-10-08 23:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/713/">test-portal-source-format#713</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/713/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/452">patriciajeanperez#452</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1567601094">[master] ci:test:sf - epark18 &gt; patriciajeanperez - PR#452 - 2021-10-08[16:53:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/2369/">publish-testray-report#2369</a><br/></div></div>

2021-10-09 00:39 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +		User.logoutAndLoginPG(
Implement Poshi Tasks so that you can explain in the intent of the test clearly through the poshi summary. See https://github.com/liferay/liferay-portal/blob/5a8f7b213cf1051414c9fbc436fc7f8b46e0ae74/modules/test/poshi/poshi-script.markdown#grouping-tasks

2021-10-09 00:58 UTC, reizero00 requested changes
@patriciajeanperez 
Left a bunch of feedback :)

2021-10-09 00:58 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +	test AccountAdminCanAssignRolesToUsers {
This test is using test@liferay.com who is actually the Super Admin of the server. If you need to test this as an Account Administrator, you'll need to create the user and have the test start there.

- [ ] Verify if the test needs to be done by the Account Administrator instead of the Super Admin
- [ ] If so, update the test accordingly

2021-10-09 00:58 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +		User.logoutAndLoginPG(
Implement Poshi Tasks so that you can explain in the intent of the test clearly through the poshi summary. See https://github.com/liferay/liferay-portal/blob/5a8f7b213cf1051414c9fbc436fc7f8b46e0ae74/modules/test/poshi/poshi-script.markdown#grouping-tasks

- [ ] Implement Poshi Tasks through test

2021-10-09 00:58 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +			AssertTextEquals(
Since adding a new user to the business account is a part of the setup of the test and not a part of the main intent you should be using waitForElementPresent and not assertions. Assertions are reserved for the main intent of the test exclusively.

- [ ] Refactor assertions to confirm the addition of a user to a business account to waitForElement

2021-10-09 00:58 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +		Accounts.addAssigneeToRoleViaUsersTab(
What's the point of having this part? Doesn't the loop do the same thing in the for loop on the second iteration?

2021-10-09 00:58 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +		for (var accountRoles : list "Test Account Role,Test Account Role 2") {
Why does this test need to repeat the process for two users and roles?

2021-10-09 00:58 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +		for (var n : list "1,2") {
I guess if you had to have two users with two roles then I think it might be easier to review if you have two separate loops:

1. The first loop will be of 2 in order to add the new users to the business accounts
2. The second loop can be used to assert that the two users were added successfully. 

What this does is it has the sections focused on the task of adding or asserting. 

Mentally it reads like this right now:

Repeat this process twice:
Add a user to the business account
Verify the user was added to the account

Versus

Add two users to the business account
Verify that the two users were actually added to the account

In these examples, you're not having to carry knowledge over (even though it's two) you just carry one piece of knowledge and then let it go for the next step.

2021-10-09 01:00 UTC, reizero00 commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +	test AccountAdminCanAssignRolesToUsers {
Also keep in mind that it's unrealistic to expect a super admin to perform these tasks. Customers are advised to disable or reconfigure the super admin account and create administrators.

2021-10-11 20:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/5172/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-source-format/builds/5172/jenkins-report.html">here</a>.</b></p>

2021-10-21 19:24 UTC, patriciajeanperez commented
Thanks @reizero00!

2021-10-21 19:24 UTC, closed without merging