LPS-165283 | master
patriciajeanperez/liferay-portal pull request #659
Opened 2022-10-12 15:26 UTC by Sharryxue

https://issues.liferay.com/browse/LPS-165283

Hello @patriciajeanperez , I know you are refactoring the organization related tests, so I only replaced the define permission macro for organization test, no additional changes for it. Hope this won't cause other conflict. Thanks in advance.

2022-10-12 15:43 UTC, Sharryxue commented
ci:test:sf

2022-10-12 15:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/5273/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5273/jenkins-report.html">here</a>.</b></p>

2022-10-12 15:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6d286cb988581204cc5cd4327333c02089d2a9cb">6d286cb988581204cc5cd4327333c02089d2a9cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Sharryxue/liferay-portal/tree/master-qa-165283">master-qa-165283</a><br/>Branch GIT ID: <a href="https://github.com/Sharryxue/liferay-portal/commit/5ac9bf63d2aaf5653cf0b707c403539c7a19dd10">5ac9bf63d2aaf5653cf0b707c403539c7a19dd10</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5273/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5273/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase expected:&lt;...nRolesAdmin();
     [java] 
     [java]     //[ ]This macro can not b...&gt; but was:&lt;...nRolesAdmin();
     [java] 
     [java]     //[]This macro can not b...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 2:00.060 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-13/job/test-portal-source-format/5273//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221012084951129.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221012084951129.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1325537819.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null349969089
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 207ms
[junitreport] Deleting: /tmp/null349969089
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-12-2022 08:49:55:487 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2022-10-12 15:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5273/">test-portal-source-format#5273</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5273/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/659">patriciajeanperez#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2004791895">[master] ci:test:sf - Sharryxue &gt; patriciajeanperez - PR#659 - 2022-10-12[08:44:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/3223/">publish-testray-report#3223</a><br/></div></div>

2022-10-12 21:28 UTC, patriciajeanperez requested changes
@Sharryxue Please see comments and SF error. Thanks!

2022-10-12 21:28 UTC, patriciajeanperez commented on portal-web/test/functional/com/liferay/portalweb/macros/RoleNavigator.macro
> +		}
@Sharryxue Can we cover these steps in Role.editPermissionCmdCP? What do you think about RoleNavigator.gotoDefinePermissions being solely for navigating to the page?

2022-10-12 21:28 UTC, patriciajeanperez commented on portal-web/test/functional/com/liferay/portalweb/macros/RoleNavigator.macro
> +		}
also might be for another ticket, but we can remove the Search for role in this macro

2022-10-13 05:58 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/RoleNavigator.macro
> +		}
Yes, it would better to only have navigating to page macro in RoleNavigator.macro file, I was thinking of the same way to see if it can helps with simplify the define permission macro, addressing it in [LPS-164631](https://issues.liferay.com/browse/LPS-164631).
Will add an addition commit to remove the search step first. Thanks Patty.

2022-10-13 12:36 UTC, Sharryxue commented
Hello @patriciajeanperez ,
I'd force pushed the changes, would you please help with review it again? Thanks in advance.
- Resolved the SF issue.
- Removed the search steps from _RoleNavigator.macro_ file
- Will work in [LPS-164631](https://issues.liferay.com/browse/LPS-164631) to move the steps and make _RoleNavigator.macro_ file only for navigate.

2022-10-13 12:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/4006/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4006/jenkins-report.html">here</a>.</b></p>

2022-10-13 12:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fa3aa4e678f16c1f1684112417b419c5b1632d41">fa3aa4e678f16c1f1684112417b419c5b1632d41</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Sharryxue/liferay-portal/tree/master-qa-165283">master-qa-165283</a><br/>Branch GIT ID: <a href="https://github.com/Sharryxue/liferay-portal/commit/dda196ab9be7abfccc6c88f1ee560ffda90a253e">dda196ab9be7abfccc6c88f1ee560ffda90a253e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/4006/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4006/jenkins-report.html">here</a>.</h5></details></html>

2022-10-13 12:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/4006/">test-portal-source-format#4006</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4006/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/659">patriciajeanperez#659</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2005727897">[master] ci:test:sf - Sharryxue &gt; patriciajeanperez - PR#659 - 2022-10-13[05:36:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/4207/">publish-testray-report#4207</a><br/></div></div>

2022-10-13 17:53 UTC, patriciajeanperez commented
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/124550

2022-10-13 17:53 UTC, closed without merging