LRQA-73706 | master
patriciajeanperez/liferay-portal pull request #685
Opened 2022-11-03 07:28 UTC by melodywu

https://issues.liferay.com/browse/LRQA-73706

2022-11-03 07:28 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-03 07:29 UTC, melodywu commented
ci:test:sf

2022-11-03 07:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/999/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/999/jenkins-report.html">here</a>.</b></p>

2022-11-03 07:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66aa734dbf43e0f8d9b0aed1543cbd1392714720">66aa734dbf43e0f8d9b0aed1543cbd1392714720</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73706-5">master-qa-73706-5</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/5804fd19315438c3727bef201af9648fdc0eb442">5804fd19315438c3727bef201af9648fdc0eb442</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/999/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/999/jenkins-report.html">here</a>.</h5></details></html>

2022-11-03 07:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/999/">test-portal-source-format#999</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/999/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/685">patriciajeanperez#685</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2031207729">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#685 - 2022-11-03[00:30:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/3221/">publish-testray-report#3221</a><br/></div></div>

2022-11-03 20:19 UTC, patriciajeanperez requested changes
@melodywu Minor changes, please see comments. Maybe we can also expand this further and add another entry that a user shouldn't be able to view? What do you think? Thanks!

2022-11-03 20:19 UTC, patriciajeanperez commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +	test ThePageActionsAreConsistentWithViewRolesPermissionsInSelectedAccount {
@melodywu Please make sure the test title and description are still accurate with the new test case

2022-11-03 20:19 UTC, patriciajeanperez commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +				userLoginFullName = "Test Test");
What is this step for?

2022-11-04 03:01 UTC, melodywu commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +	test ThePageActionsAreConsistentWithViewRolesPermissionsInSelectedAccount {
Done

2022-11-04 03:02 UTC, melodywu commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +				userLoginFullName = "Test Test");
Done

2022-11-04 03:02 UTC, melodywu commented
ci:test:sf

2022-11-04 03:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3684/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3684/jenkins-report.html">here</a>.</b></p>

2022-11-04 03:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/051154382e4ca91fa21c5dd67ecdc924050d3546">051154382e4ca91fa21c5dd67ecdc924050d3546</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73706-5">master-qa-73706-5</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/d604ab605b4a06bbc3831cf2ff52690cf99ae552">d604ab605b4a06bbc3831cf2ff52690cf99ae552</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3684/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3684/jenkins-report.html">here</a>.</h5></details></html>

2022-11-04 03:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3684/">test-portal-source-format#3684</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3684/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/685">patriciajeanperez#685</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2033101460">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#685 - 2022-11-03[20:02:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/14250/">publish-testray-report#14250</a><br/></div></div>

2022-11-08 23:41 UTC, patriciajeanperez commented
Just started reviewing :)

2022-11-09 02:45 UTC, patriciajeanperez commented
@melodywu Please see changes in https://github.com/patriciajeanperez/liferay-portal/pull/689. Please make use of other JSON macros to simplify test steps. Let me know if you have any questions!

2022-11-09 02:45 UTC, closed without merging