LRQA-72141 | master
patriciajeanperez/liferay-portal pull request #692
Opened 2022-11-10 08:38 UTC by melodywu

https://issues.liferay.com/browse/LRQA-72141

2022-11-10 08:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-10 08:39 UTC, melodywu commented
ci:test:sf

2022-11-10 08:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/2065/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2065/jenkins-report.html">here</a>.</b></p>

2022-11-10 08:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57f7d9a5024f39fb59e8ac7de03cc2c0bd3d36dd">57f7d9a5024f39fb59e8ac7de03cc2c0bd3d36dd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-72141">master-qa-72141</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/78c844b1bfa1664ff0006963c8f893bf85fc6579">78c844b1bfa1664ff0006963c8f893bf85fc6579</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2065/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2065/jenkins-report.html">here</a>.</h5></details></html>

2022-11-10 08:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2065/">test-portal-source-format#2065</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2065/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/692">patriciajeanperez#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2044265087">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#692 - 2022-11-10[00:39:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/7785/">publish-testray-report#7785</a><br/></div></div>

2022-11-10 19:23 UTC, patriciajeanperez commented
Hey @melodywu, please review and make sure all set up are in the Given block.

2022-11-11 07:15 UTC, melodywu commented
ci:test:sf

2022-11-11 07:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/3725/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3725/jenkins-report.html">here</a>.</b></p>

2022-11-11 07:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f849d60b693d90f9cffbc23f9d1c68eb2ab0e1d4">f849d60b693d90f9cffbc23f9d1c68eb2ab0e1d4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-72141">master-qa-72141</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/7841529cc5d33ae97bb02604cb7c970472baba4c">7841529cc5d33ae97bb02604cb7c970472baba4c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3725/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3725/jenkins-report.html">here</a>.</h5></details></html>

2022-11-11 07:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3725/">test-portal-source-format#3725</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3725/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/692">patriciajeanperez#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2047132065">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#692 - 2022-11-10[23:15:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/13698/">publish-testray-report#13698</a><br/></div></div>

2022-11-11 18:08 UTC, patriciajeanperez requested changes
@melodywu Nice work, Melody! Please review all the tests again to make sure that we are removing unnecessary steps. 

These steps may be added before this change, but when we are refactoring, we want to take this chance to take a look at the entire test and see how we can improve them. In this case, when we apply BDD to the test, it can help us highlight which steps we can remove to simplify the test.

I saw a lot of log out and log in steps that these tests do not really need. Please review them one by one before resending. Thank you.

cc @sharryxue

2022-11-11 18:08 UTC, patriciajeanperez commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
>  				userLoginFullName = "Test Test");
@melodywu Please review the steps here

2022-11-11 18:09 UTC, patriciajeanperez commented
@melodywu Please also write all the tickets in the title and description of the PR. It looks like this PR is working on two subtasks but only one is written here.

2022-11-17 05:50 UTC, melodywu commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +		task ("adds account via widget as Account Admin") {
Done and thanks

2022-11-17 05:56 UTC, melodywu commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +			Navigator.gotoPage(pageName = "2B Account Page");
Done and thank

2022-11-17 05:57 UTC, melodywu commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +			Navigator.gotoPage(pageName = "2B Account Page");
Done

2022-11-17 06:02 UTC, melodywu commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
> +			Navigator.gotoPage(pageName = "2B Account Page");
Done

2022-11-17 06:03 UTC, melodywu commented on modules/apps/account/account-test/src/testFunctional/tests/AccountPermissions.testcase
>  				userLoginFullName = "Test Test");
done

2022-11-17 06:30 UTC, melodywu commented
ci:test:sf

2022-11-17 06:30 UTC, melodywu commented
ci:test

2022-11-17 06:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/3066/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3066/jenkins-report.html">here</a>.</b></p>

2022-11-17 06:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/4106/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4106/jenkins-report.html">here</a>.</b></p>

2022-11-17 06:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7981e83f8002dec2719622319ec5efc72b279042">7981e83f8002dec2719622319ec5efc72b279042</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-72141">master-qa-72141</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/9cca8c3e43a45984f60cbed93d3db20678601e49">9cca8c3e43a45984f60cbed93d3db20678601e49</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4106/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4106/jenkins-report.html">here</a>.</h5></details></html>

2022-11-17 06:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4106/">test-portal-source-format#4106</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4106/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/692">patriciajeanperez#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2059547665">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#692 - 2022-11-16[22:30:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/15165/">publish-testray-report#15165</a><br/></div></div>

2022-11-17 07:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:default - 4 out of 4 jobs passed in 1 hour 24 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7981e83f8002dec2719622319ec5efc72b279042">7981e83f8002dec2719622319ec5efc72b279042</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7981e83f8002dec2719622319ec5efc72b279042">7981e83f8002dec2719622319ec5efc72b279042</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2057741406">EE Development Acceptance (master) - 4029 - 2022-11-16[07:41:46]</a></p><details><summary><strong>ci:test:default - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/3066/">test-portal-acceptance-pullrequest(master)</a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/292500/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/321736/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344298/">functional-tomcat90-mysql57-jdk8/0/2</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3066/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/3066/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/3066/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/3066/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-11-17 07:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/3066/">test-portal-acceptance-pullrequest(master)#3066</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3066/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/692">patriciajeanperez#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2059561344">[master] ci:test:default - melodywu &gt; patriciajeanperez - PR#692 - 2022-11-16[22:30:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/7038/">publish-testray-report#7038</a><br/></div></div>

2022-11-17 08:23 UTC, melodywu commented
ci:test:sf

2022-11-17 08:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/1238/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1238/jenkins-report.html">here</a>.</b></p>

2022-11-17 08:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7981e83f8002dec2719622319ec5efc72b279042">7981e83f8002dec2719622319ec5efc72b279042</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-72141">master-qa-72141</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/c140143ed4a91c281cc1c35dc2aab9115976316c">c140143ed4a91c281cc1c35dc2aab9115976316c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1238/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1238/jenkins-report.html">here</a>.</h5></details></html>

2022-11-17 08:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1238/">test-portal-source-format#1238</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1238/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/692">patriciajeanperez#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2059594301">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#692 - 2022-11-17[00:23:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/3425/">publish-testray-report#3425</a><br/></div></div>

2022-11-22 22:21 UTC, patriciajeanperez commented
ci:forward

2022-11-22 22:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-11-22 22:21 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-11-22 22:22 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/617//consoleFull)

2022-11-22 22:22 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/126698
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/617//consoleFull)

2022-11-22 22:22 UTC, closed without merging