LRQA-68075 | master
patriciajeanperez/liferay-portal pull request #702
Opened 2022-11-18 02:13 UTC by melodywu

https://issues.liferay.com/browse/LRQA-68075

2022-11-18 02:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-18 02:13 UTC, melodywu commented
ci:test:sf

2022-11-18 02:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/4922/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4922/jenkins-report.html">here</a>.</b></p>

2022-11-18 02:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/abd69858a8591c40a67917cdf0d7e49e39974577">abd69858a8591c40a67917cdf0d7e49e39974577</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-68075">master-qa-68075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/b6a825c0db29476282ce673bdb8b5313c4e9adea">b6a825c0db29476282ce673bdb8b5313c4e9adea</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4922/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4922/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase expected:&lt;...\}
     [java]   \}
     [java] 
     [java]   @priority = "[5"
     [java]   test AnonymizeEntryFromApplication \{
     [java]     property portal.acceptance = "true";
     [java] 
     [java]     DMNavigator.openDocumentsAndMediaAdmin(siteURLKey = "guest");
     [java] 
     [java]     DMDocument.addCP(
     [java]       dmDocumentDescription = "DM Document Description",
     [java]       dmDocumentFile = "Document_1.txt",
     [java]       dmDocumentTitle = "DM Document Title");
     [java] 
     [java]     User.logoutAndLoginPG(
     [java]       userLoginEmailAddress = "test@liferay.com",
     [java]       userLoginFullName = "Test Test");
     [java] 
     [java]     User.openUsersAdmin();
     [java] 
     [java]     User.deletePersonalDataCP(
     [java]       userFirstName = "userfn",
     [java]       userLastName = "userln");
     [java] 
     [java]     GDPR.anonymizeDataViaReviewData(application = "Documents and Media");
     [java] 
     [java]     DMNavigator.openDocumentsAndMediaAdmin(siteURLKey = "guest");
     [java] 
     [java]     DMNavigator.gotoDocumentCP(dmDocumentTitle = "DM Document Title");
     [java] 
     [java]     DMDocument.expandInfo();
     [java] 
     [java]     AssertTextEquals(
     [java]       locator1 = "DocumentsAndMediaDocument#DOCUMENT_INFO_UPLOADER_NO_PROFILE",
     [java]       value1 = "Anonymous Anonymous");
     [java]   \}
     [java] 
     [java]   @priority = "4"
     [java]   test AnonymizeMultipleEntries \{
     [java]     JSONBlog.addEntry(
     [java]       entryContent = "Blogs Entry Content",
     [java]       entryTitle = "Blogs Entry Title",
     [java]       userEmailAddress = "userea@liferay.com",
     [java]       userPassword = "test");
     [java] 
     [java]     JSONWebcontent.addFolder(
     [java]       folderName = "WC GDPR Folder",
     [java]       groupName = "Guest",
     [java]       userEmailAddress = "userea@liferay.com",
     [java]       userPassword = "test");
     [java] 
     [java]     JSONWebcontent.addWebContent(
     [java]       content = "This is a WC Content for GDPR Anonymize testing.",
     [java]       folderName = "WC GDPR Folder",
     [java]       groupName = "Guest",
     [java]       title = "GDPR Anonymize Article in Folder",
     [java]       userEmailAddress = "userea@liferay.com",
     [java]       userPassword = "test");</pre></details></html>

2022-11-18 02:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4922/">test-portal-source-format#4922</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4922/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/702">patriciajeanperez#702</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2061615712">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#702 - 2022-11-17[18:14:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/17622/">publish-testray-report#17622</a><br/></div></div>

2022-11-18 02:37 UTC, melodywu commented
ci:test:sf

2022-11-18 02:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3868/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3868/jenkins-report.html">here</a>.</b></p>

2022-11-18 02:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/abd69858a8591c40a67917cdf0d7e49e39974577">abd69858a8591c40a67917cdf0d7e49e39974577</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-68075">master-qa-68075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/7a6135517c7a0e5c92a4966681843d68f0929adb">7a6135517c7a0e5c92a4966681843d68f0929adb</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3868/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3868/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     [java] SLF4J: Defaulting to no-operation (NOP) logger implementation
     [java] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[stopwatch] [run.batch.test.action: 1:07.999 sec]
     [echo] 
      [get] Getting: http://test-1-37/job/test-portal-source-format/3868//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221117184045606.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221117184045606.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null175108110.properties</pre></details></html>

2022-11-18 03:11 UTC, melodywu commented
ci:test:sf

2022-11-18 03:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3378/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3378/jenkins-report.html">here</a>.</b></p>

2022-11-18 03:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/abd69858a8591c40a67917cdf0d7e49e39974577">abd69858a8591c40a67917cdf0d7e49e39974577</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-68075">master-qa-68075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/79e60f5a102870535a444cb029d8cd019d4d139d">79e60f5a102870535a444cb029d8cd019d4d139d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3378/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3378/jenkins-report.html">here</a>.</h5></details></html>

2022-11-18 03:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3378/">test-portal-source-format#3378</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3378/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/702">patriciajeanperez#702</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2061744034">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#702 - 2022-11-17[19:11:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/12532/">publish-testray-report#12532</a><br/></div></div>

2022-12-12 03:01 UTC, Sharryxue commented
Just starting review.

2022-12-12 03:22 UTC, Sharryxue requested changes
Hello @melodywu,
Not sure if I missing any further communication based on the issue, correct me if I did, but based on the description in the related issue, 

> Rename GDPR#ExportAllEntries to GDPR#CanExportMultipleEntries
> Rename existing tests

We should pay attention to following places,
1. Name the test in SACRED model. ExportAllEntries to **Can**ExportMultipleEntries
2. Rename the all entries to multiple entries, ExportAllEntries to **Can**Export**Multiple**Entries
3. Rename other existing test based on above principles, update the test name not only for those contains all entries but also for those name not in SACRED model

2022-12-12 03:22 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +	test ExportMultipleEntries {
Name it in SACRED model.

2022-12-14 03:14 UTC, melodywu commented
@Sharryxue  I list the names. Is there anyone I need to update?
CanAnonymizeAllEntriesFromAnApplication
CanAnonymizeARelatedAsset
CanAnonymizeASingleStagedAndLiveWebContentEntry
CanAnonymizeEntriesFromAnApplicationWithHierarchy
CanAnonymizeEntryFromApplication
CanAnonymizeMultipleEntries
CanAnonymizeMultipleEntriesFromAnApplication
CanAnonymizeMultipleStagedDataFromDM
CanAnonymizeViaInfoPanel
CanAppsWithNoEntriesAreDisabledInNewDataExport

CanDeleteAndAnonymizeMultipleEntries
CanDeleteAnExportProcess
CanDeleteARelatedAsset
CanDeleteASingleStagedAndLiveBlogsEntry
CanDeleteEntriesFromAnApplicationWithHierarchy
CanDeleteEntryFromApplication
CanDeleteMultipleEntriesFromAnApplication
CanDeleteMultipleEntriesFromInstanceScope
CanDeleteMultipleEntriesFromPersonalSiteScope
CanDeleteMultipleEntriesFromRegularSitesScope
CanDeleteMultipleStagedDataFromAnApplication
CanDisplayEntryDetailsInInfoPanel

CanEditEntryFromApplication
CanExportMultipleEntries
CanFilterAndOrderExportProcesses 
CanFilterAndViewData
CanOrderDataInViewData
CanPublishToLiveADeletedLiveEntry
EntriesAreStillAnonymousAfterActivatingUser
PaginationWorksInExportPersonalData
PaginationWorksInNewDataExport
RemainingItemsCountIsAccurate

2022-12-14 03:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4245/">test-portal-source-format#4245</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4245/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/702">patriciajeanperez#702</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2126343484">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#702 - 2022-12-13[19:14:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/16281/">publish-testray-report#16281</a><br/></div></div>

2022-12-14 23:50 UTC, melodywu commented
ci:test:sf

2022-12-14 23:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/3400/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3400/jenkins-report.html">here</a>.</b></p>

2022-12-14 23:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c33512e8dcdd2be3baefcfc741dd9e55b484dc53">c33512e8dcdd2be3baefcfc741dd9e55b484dc53</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-68075">master-qa-68075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/ab1fc538788fe06e4e114fae0fe42a1edbad8f9b">ab1fc538788fe06e4e114fae0fe42a1edbad8f9b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3400/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3400/jenkins-report.html">here</a>.</h5></details></html>

2022-12-14 23:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3400/">test-portal-source-format#3400</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3400/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/702">patriciajeanperez#702</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2128991718">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#702 - 2022-12-14[15:52:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/11733/">publish-testray-report#11733</a><br/></div></div>

2023-02-01 23:19 UTC, patriciajeanperez commented
Thanks, @melodywu! For next time, I think it would be nice to separate these into different commits to make it easy to review. Please see https://github.com/patriciajeanperez/liferay-portal/pull/737.

2023-02-01 23:19 UTC, closed without merging

2023-02-02 00:28 UTC, melodywu commented
> Thanks, @melodywu! For next time, I think it would be nice to separate these into different commits to make it easy to review. Please see #737.

Ok， thank you Patty！