LRQA-73479 | master
patriciajeanperez/liferay-portal pull request #719
Opened 2023-01-04 08:03 UTC by melodywu

https://issues.liferay.com/browse/LRQA-73479

2023-01-04 08:03 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-04 08:03 UTC, melodywu commented
ci:test:sf

2023-01-04 08:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/5516/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5516/jenkins-report.html">here</a>.</b></p>

2023-01-04 08:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/951449dc2f2b7bd22d223aa3d887f74b20ee6434">951449dc2f2b7bd22d223aa3d887f74b20ee6434</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73479-1">master-qa-73479-1</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/43b4c960adbddb586848142a1b91c6770e672407">43b4c960adbddb586848142a1b91c6770e672407</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5516/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5516/jenkins-report.html">here</a>.</h5><pre>     [java] Caused by: java.lang.RuntimeException: Unable to format ./portal-web/test/functional/com/liferay/portalweb/macros/User.macro
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:717)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.access\$000(BaseSourceProcessor.java:77)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:109)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:105)
     [java]   ... 4 more
     [java] Caused by: java.lang.Exception
     [java]   at com.liferay.poshi.core.script.PoshiScriptParserException.throwExceptions(PoshiScriptParserException.java:79)
     [java]   at com.liferay.source.formatter.processor.PoshiSourceProcessor.parse(PoshiSourceProcessor.java:126)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:313)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:357)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:276)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._format(BaseSourceProcessor.java:603)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:705)
     [java]   ... 7 more
     [java] 
     [java] 
     [java] Poshi parsing errors in /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/User.macro
     [java] 
     [java] Invalid Poshi Script syntax at:
     [java] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/User.macro:6
     [java]    1 |definition \{
     [java]    2 |
     [java]    3 |    var password = "test";
     [java]    4 |    var userEmailAddress = "test@liferay.com";
     [java]    5 |
     [java]  &gt; 6 |    macro  \{
     [java]    7 |        Type(
     [java]    8 |            locator1 = "UsersAndOrganizationsEditUser#DETAILS_SCREEN_NAME_FIELD",
     [java]    9 |            value1 = "\$\{userScreenName\}");
     [java]   10 |
     [java]   11 |        Type(
     [java]   12 |            locator1 = "UsersAndOrganizationsEditUser#DETAILS_EMAIL_ADDRESS_FIELD",
     [java]   13 |            value1 = "\$\{userEmailAddress\}");
     [java] 
     [java] 
     [java] </pre></details></html>

2023-01-06 16:28 UTC, patriciajeanperez commented on portal-web/test/functional/com/liferay/portalweb/macros/Organization.macro
Hi @melodywu, any reason you did not want to include these in your new macro?

2023-01-09 05:37 UTC, melodywu commented on portal-web/test/functional/com/liferay/portalweb/macros/Organization.macro
Yes， you are right. At first I think I should add “Mandatory filed” but I am wrong, If I add if condition sentence I can add the other field.

2023-01-09 07:03 UTC, melodywu commented
ci:test:sf

2023-01-09 07:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/4695/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4695/jenkins-report.html">here</a>.</b></p>

2023-01-09 07:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f432b9e8a6df4a1975f64544b8fff8af539e1291">f432b9e8a6df4a1975f64544b8fff8af539e1291</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73479-1">master-qa-73479-1</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/046016c8519f7bdcf1d05b0e870e72b9e16b6154">046016c8519f7bdcf1d05b0e870e72b9e16b6154</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4695/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4695/jenkins-report.html">here</a>.</h5><pre>     [java] Caused by: java.lang.RuntimeException: Unable to format ./portal-web/test/functional/com/liferay/portalweb/macros/User.macro
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:717)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.access\$000(BaseSourceProcessor.java:77)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:109)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:105)
     [java]   ... 4 more
     [java] Caused by: com.liferay.poshi.core.script.UnbalancedCodeException: Unexpected closing boundary at:
     [java] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/User.macro:2991
     [java]   at com.liferay.poshi.core.script.PoshiScriptParserUtil.isBalancedPoshiScript(PoshiScriptParserUtil.java:223)
     [java]   at com.liferay.poshi.core.elements.PoshiNodeFactory.newPoshiNode(PoshiNodeFactory.java:109)
     [java]   at com.liferay.source.formatter.processor.PoshiSourceProcessor.parse(PoshiSourceProcessor.java:114)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:313)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:276)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._format(BaseSourceProcessor.java:603)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:705)
     [java]   ... 7 more
[stopwatch] [run.batch.test.action: 50.669 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-37/job/test-portal-source-format/4695//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230108230523618.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230108230523618.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.</pre></details></html>

2023-01-09 09:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4695/">test-portal-source-format#4695</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4695/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/patriciajeanperez/liferay-portal/pull/719">patriciajeanperez#719</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2153117984">[master] ci:test:sf - melodywu &gt; patriciajeanperez - PR#719 - 2023-01-08[23:03:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/17961/">publish-testray-report#17961</a><br/></div></div>

2023-01-09 20:01 UTC, patriciajeanperez requested changes
Hi @melodywu! Looks good, I just left a few comments. Please validate and SF before re-sending. We can also run the test suite for all Users and Orgs tests given that the macros we are updating are widely used. Thanks!

2023-01-10 01:20 UTC, melodywu commented on portal-web/test/functional/com/liferay/portalweb/macros/User.macro
Ok thanks

2023-01-10 01:20 UTC, melodywu commented on portal-web/test/functional/com/liferay/portalweb/macros/User.macro
> +				userScreenName = "${userScreenName}");
Ok thanks

2023-01-10 01:20 UTC, closed without merging